on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Package

env:
  NODE_VERSION: 20

jobs:
  package:
    name: Package distribution files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Package
        run: npm run package

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Update dist" || echo "No changes to commit"
          git push origin main
